name: Build Debian package

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['master', 'main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
# env:
#  REGISTRY: git.marcorealacci.me
#  USER: marco-private

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        run: apt-get update && apt-get install build-essential

      - name: Build Debian package
        run: dpkg-buildpackage -us -uc -b  --target-arch amd64

      # - name: Call webhook
      #   run: curl -X POST ${{secrets.DEPLOY_WEBHOOK}}
